import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Disclaimer | ExportForm",
  description: "Legal disclaimer regarding the use of ExportForm for generating draft EDF documents.",
};

export default function DisclaimerPage() {
  return (
    <div className="flex flex-col min-h-screen bg-background text-foreground font-sans">
      <header className="px-6 py-8 max-w-4xl mx-auto w-full border-b border-border/50">
        <Link href="/" className="text-xl font-semibold tracking-tight text-foreground hover:text-accent transition-colors">
          &larr; ExportForm
        </Link>
      </header>

      <main className="flex-1 max-w-3xl mx-auto px-6 py-16 w-full">
        <article className="prose prose-slate md:prose-lg max-w-none">
          <h1 className="text-4xl font-bold tracking-tight mb-8">Disclaimer</h1>
          
          <h2 className="text-2xl font-semibold mt-10 mb-4">Not Official Advice</h2>
          <p>
            ExportForm is an independent software tool designed to help you format your service export information into a clean PDF. We are <strong>not</strong> affiliated with the Reserve Bank of India (RBI), the Government of India, any Authorized Dealer (AD) Category-I bank, or any other regulatory body.
          </p>
          <p>
            The information generated by ExportForm does not constitute legal, tax, or financial advice.
          </p>

          <h2 className="text-2xl font-semibold mt-10 mb-4">Draft Status</h2>
          <p>
            Documents generated by ExportForm are clearly marked as <strong>"DRAFT / PREVIEW"</strong>. We do not claim that the output of this software is a 100% compliant official RBI document. The format required for inward remittance declarations may vary significantly depending on your specific bank branch and the nature of your exports.
          </p>

          <h2 className="text-2xl font-semibold mt-10 mb-4">User Responsibility</h2>
          <p>
            It is your sole responsibility to:
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li>Verify the accuracy of the information you enter.</li>
            <li>Confirm the exact documentation required by your authorized dealer bank before submission.</li>
            <li>Ensure compliance with all applicable FEMA (Foreign Exchange Management Act) regulations.</li>
          </ul>

          <h2 className="text-2xl font-semibold mt-10 mb-4">No Liability</h2>
          <p>
            ExportForm is provided "as is" without warranties of any kind. Under no circumstances shall the creators of ExportForm be held liable for any damages, delayed remittances, rejected documents, or regulatory penalties arising from the use of this tool.
          </p>
        </article>
      </main>
    </div>
  );
}
